version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

  lint:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint

  buildapk:
    docker:
      - image: kusumoto/docker-ionic-android-sdk
    working_dirictory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          command: yes | /opt/android-sdk/tools/bin/sdkmanager --licenses || true
          name: "Accept Android SDK Licenses"

      - restore_cache:
          keys:
            - v1-cordova-{{ checksum "config.xml" }}
      
      - run:
          command: echo $GOOGLE_SERVICES | base64 --decode > ${HOME}/repo/platforms/android/app/google-services.json
          name: "Import Google Firebase config"
      
      - run:
          command: ionic cordova compile
          name: "First Cordova compile"
          
      - save_cache:
          paths:
            - node_modules
          key: v1-cordova-{{ checksum "config.xml" }}
          
      - run:
          command: ionic cordova build android
          name: "Build APK with Cordova"

      - store_artifacts:
          path: platforms/android/build/outputs/apk/app-debug.apk
          destination: Android App

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
      - buildapk:
          requires:
            - lint
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
